#cloud-config

users:
  - name: admin
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7GCkVUEdjEc2isuh/TkPDCyNWHYxM/VN0C2kPy94Uk

disable_root: true
ssh_pwauth: false

package_update: true
package_upgrade: true

timezone: Europe/Warsaw

packages:
  - curl

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - apt-get install -y docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker

