services:
  nginx:
    image: ghcr.io/tomektarczynski/personal-server/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: ghcr.io/tomektarczynski/personal-server/api:latest
    env_file:
      - /etc/personal-server/personal-server.env
    environment:
      - PORT=8000
      - DB_PATH=/data/sqlite.db
      - BACKUP_DIR=/var/backups/personal-server
    volumes:
      - appdata:/data
    expose:
      - "8000"
    restart: unless-stopped

volumes:
  appdata: